name: Convert JSON to CSV and GeoJSON

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の午前0時に実行
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          
      - name: Install Python dependencies
        run: pip install requests

      - name: JSONをCSVとGeoJSONに変換するスクリプトを実行
        run: |
          python convert_json_to_csv.py

      - name: 変更をコミットしてプッシュ
        run: |
          git config --local user.email "y.shiwaku.5519@gmail.com"
          git config --local user.name "shi-works"
          git add amedastable.csv amedastable.geojson
          git status  # 状態を確認
          git commit -m "Update CSV and GeoJSON files from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
