name: Amedas-Data Convert CSV to GeoJSON

on:
  schedule:
    - cron: '55 * * * *'  # 毎時55分に実行
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          
      - name: Install Python dependencies
        run: pip install requests pandas

      - name: JSONをCSVとGeoJSONに変換するスクリプトを実行
        run: python amedas-data-get.py

      - name: 変更をコミットしてプッシュ
        run: |
          git config --local user.email "y.shiwaku.5519@gmail.com"
          git config --local user.name "shiwaku"
          git add amedastable.csv amedastable.geojson
          
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update CSV and GeoJSON files"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
